### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by mhbodell** [lejon/PartiallyCollapsedLDA#13]
exmaple is README:
`java -cp PCPLDA-4.7.3.jar cc.mallet.topics.tui.ParallelLDA --run_cfg=src/main/resources/configuration/PLDAConfig.cfg`

can be updated to:

`java -cp PCPLDA-8.0.11.jar cc.mallet.topics.tui.ParallelLDA --run_cfg=src/main/resources/configuration/PLDAConfig.cfg`

**Comment by lejon** [comment]
Thanks for that! Fixed.
