### ISSUE TITLE
Formally psi should be Psi to be coherent with notation

### ISSUE THREAD

**Issue by MansMeg** [lejon/PartiallyCollapsedLDA#5]
https://github.com/lejon/PartiallyCollapsedLDA/blob/7d3290d63d7fe308440e4194820cadfa991c3fad/src/main/java/cc/mallet/topics/PoissonPolyaUrnHDPLDA.java#L49

**Comment by lejon** [comment]
Java coding conventions dictate that variable names start with a small letter
