### ISSUE TITLE
Ths should be alpha*phi*psi I believe

### ISSUE THREAD

**Issue by MansMeg** [lejon/PartiallyCollapsedLDA#7]
https://github.com/lejon/PartiallyCollapsedLDA/blob/7d3290d63d7fe308440e4194820cadfa991c3fad/src/main/java/cc/mallet/topics/PoissonPolyaUrnHDPLDA.java#L71

**Comment by lejon** [comment]
This is removed in cleanup, and that is in fact how it is calculated in that implementation
