### ISSUE TITLE
The same her? maxTopics?

### ISSUE THREAD

**Issue by MansMeg** [lejon/PartiallyCollapsedLDA#9]
https://github.com/lejon/PartiallyCollapsedLDA/blob/7d3290d63d7fe308440e4194820cadfa991c3fad/src/main/java/cc/mallet/topics/PoissonPolyaUrnHDPLDA.java#L107

Should not this allocate maxTopics as well?

**Comment by lejon** [comment]
numTopics **is** the maxTopics, so it should be correct.
